export const GET_CATEGORY = "GET_CATEGORY";
export const SAVE_CATEGORY = "SAVE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const HANDLE_CHANGE_CATEGORY = "HANDLE_CHANGE_CATEGORY";
