export const GET_PUBLISHER = "GET_PUBLISHER";
export const SAVE_PUBLISHER = "SAVE_PUBLISHER";
export const DELETE_PUBLISHER = "DELETE_PUBLISHER";
export const HANDLE_CHANGE_PUBLISHER = "HANDLE_CHANGE_PUBLISHER";
